### ISSUE TITLE
AttributeError: 'Axes3DSubplot' object has no attribute 'set_box_aspect'

### ISSUE THREAD

**Issue by programmer-04** [pclausen/obj2png#11]
Running the script gave me throws this error. I suspect it is because of a version mismatch.
I think you should specify version numbers in your requirements.txt

Traceback (most recent call last):
  File "obj2png/src/obj2png.py", line 122, in <module>
    ob.Plot(outfile,elevation=elevation,azim=azim,dpi=dpi,scale=scale,animate=animate)
  File "/content/obj2png/src/ObjFile.py", line 184, in Plot
    ax.set_box_aspect(np.ptp(limits, axis = 1))
AttributeError: 'Axes3DSubplot' object has no attribute 'set_box_aspect'`

**Comment by pclausen** [comment]
@programmer-04 Which version of Python and matplotlib are you using ?

>  I think you should specify version numbers in your requirements.txt

I probably should but I was expecting most versions to work so I did not want to block anyone on older systems.
